server:
  port: 8091



spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: mustafa
    password: 123
  data:
    mongodb:
      host: 35.184.169.123
      port: 14806
      database: userDb
      username: bilge
      password: bilge
  zipkin:
    enabled: true
    base-url: http://localhost:9411
    service:
      name: user-service

  #  datasource:
  #    username: 'postgres'
  #    password: 'root'
  #    driver-class-name: org.postgresql.Driver
  #    url: 'jdbc:postgresql://localhost:5432/socialMediaUser'

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true



#Jwt


secretkey: ${secretkey}
audience: ${audience}
issuer: ${issuer}


redis:
  host: localhost
  port: 6379


myapplication:
  feign:
    auth: http://localhost:8090/api/v1
    elastic: http://localhost:8099/api/v1

rabbitmq:
  exchange-user: user-excahange
  userUpdateBindingKey: user-update-key
  userUpdateQueue: user-update-queue
  userUpdateQueueElastic: user-update-queue-elastic
  userUpdateBindingKeyElastic: user-update-key-elastic