spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: mustafa
    password: 123
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${gmailsmtpmail}
    password: ${gmailsmptpassword}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

rabbitmq:
  queueAcvitavted: activated-queue