server:
  port: 8093

spring:
  data:
    mongodb:
      host: 35.184.169.123
      port: 14806
      database: postDb
      username: bilge
      password: bilge
  zipkin:
    enabled: true
    base-url: http://localhost:9411
    service:
      name: post-service

#Jwt
secretkey: ${secretkey}
audience: ${audience}
issuer: ${issuer}

myapplication:
  feign:
    auth: http://localhost:8090/api/v1
    elastic: http://localhost:8099/api/v1