server:
  port: ${auth-port}

spring:
  rabbitmq:
    host: ${rabbitmq-host}
    port: ${rabbitmq-port}
    username: ${rabbitmq-username}
    password: ${rabbitmq-password}
  zipkin:
    enabled: true
    base-url: ${zipkin-url}
    service:
      name: auth-service
  datasource:
    username: ${db_postgresql_username}
    password: ${db_postgresql_password}
    driver-class-name: org.postgresql.Driver
    url: ${db_postgresql_url}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


#Jwt


secretkey: ${secretkey}
audience: ${audience}
issuer: ${issuer}

redis:
  host: ${redis_host}
  port: ${redis_port}

myapplication:
  feign:
    user: ${myapplication.feign.user}
    elastic: ${myapplication.feign.elastic}


rabbitmq:
  exchange-auth: ${exchange-auth}
  bindingKey: ${bindingKey}
  queueAcvitavted: ${queueAcvitavted}
  userUpdateQueue: ${userUpdateQueue}