server:
  port: 8889

spring:
  application:
    name: config-server-git
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/mustafaozturk0614/configserverlist"
          default-label: main
          skip-ssl-validation: true
          username: "mustafaozturk0614"
          password: "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"