apiVersion: v1
kind: Secret
metadata:
  name: socialmediasecret
type: Opaque
stringData:
  db_postgresql_username: "postgres"
  db_postgresql_password: "password"
  db_postgresql_url: "jdbc:postgresql://10.4.0.54/authdb"
  db_mongo_username: "bilge"
  db_mongo_password: "bilge"
  db_mongo_host: "35.184.169.123"
  db_mongo_port: "14806"
  db_mongo_userdb: "userDb"
  db_mongo_postdb: "postDb"
  auth-service-clusterip: "10.8.11.164"
  user-service-clusterip: "10.8.1.35"
  post-service-clusterip: "10.8.12.86"
  mail-service-clusterip: "10.8.5.247"
  elastic-service-clusterip: "10.8.1.88"
  config-service-clusterip: "10.8.1.168"
  gatewap-service-loadbalancer: "34.69.175.233"
  rabbitmq-host: "10.4.0.51"
  rabbitmq-port: "5672"
  rabbitmq-username: "socialmedia"
  rabbitmq-password: "socialmedia123*"
  zipkin-url: "http://10.4.0.53:9411"
  auth-port: "8090"
  user-port: "8091"
  post-port: "8092"
  mail-port: "8094"
  gateway-port: "80"
  elastic-port: "8099"
  config-port: "8888"
  secretkey: "secretkey"
  audience: "bilgeadam"
  issuer: "mustafa"
  redis-host: "10.4.0.52"
  redis-port: "6379"
  myapplication-feign-user: http://10.8.1.35:8091/api/v1
  myapplication-feign-auth: http://10.8.11.164:8090/api/v1
  myapplication-feign-elastic: http://10.8.1.88:8099/api/v1
  myapplication-feign-post: http://10.8.12.86:8092/api/v1
  myapplication-feign-mail: http://10.8.5.247:8094/api/v1
  rabbitmq-exchange-auth: auth-excahange
  rabbitmq-bindingKey: activated-key
  rabbitmq-queueAcvitavted: activated-queue
  rabbitmq-userUpdateQueue: user-update-queue
  rabbitmq-userUpdateQueueElastic: user-update-queue-elastic
  rabbitmq-exchange-user: user-excahange
  rabbitmq-userUpdateBindingKey: user-update-key
  rabbitmq-userUpdateBindingKeyElastic: user-update-key-elastic
  elastic-service-uri: http://10.8.1.88:9200
  config-server-url: http://10.8.1.168:8888
  auth-service-url: http://10.8.11.164:8090
  post-service-url: http://10.8.12.86:8092
  user-service-url: http://10.8.1.35:8091
  elastic-service-url: http://10.8.1.88:8099
  mail-service-url: http://10.8.5.247:8094
