apiVersion: apps/v1
kind: Deployment
metadata:
  name: configserverdeployment
  labels:
    team: socialmediadev
spec:
  selector:
    matchLabels:
      app: config-service
  template:
    metadata:
      labels:
        app: config-service
    spec:
      containers:
        - name: config-server-container
          image: musty1406/config-serverj3:v002
          resources:
            requests:
              memory: "128Mi"
              cpu: "0.1"
            limits:
              memory: "512Mi"
              cpu: "0.2"
          ports:
            - containerPort: 8888
          env:
            - name: config-port
              valueFrom:
                secretKeyRef:
                  name: socialmediasecret
                  key: config-port
            - name: zipkin-url
              valueFrom:
                secretKeyRef:
                  name: socialmediasecret
                  key: zipkin-url
