apiVersion: v1
kind: Service
metadata:
  name: api-gateway-loadbalancer
spec:
  type: LoadBalancer
  selector:
    app: api-gateway

  ports:
    - port: 80
      targetPort: 80
      name: api-gateway-port
