apiVersion: v1
kind: Service
metadata:
  name: config-cluster
spec:
  type: ClusterIP
  selector:
    app: config-service
  ports:
    - port: 8888
      targetPort: 8888
      name: config-service-port
