apiVersion: v1
kind: Service
metadata:
  name: elastic-cluster
spec:
  type: ClusterIP
  selector:
    app: elastic-service
  ports:
    - port: 8099
      targetPort: 8099
      name: elastic-service-one
    - port: 9200
      targetPort: 9200
      name: elastic-service-two
